### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by kobic8** [autodistill/autodistill-dinov2#1]
a broken link on readme file for: https://autodistill.github.io/autodistill/base_models/dinov2/

**Comment by computerscienceiscool** [comment]
Updated the Readme.md to have the https://autodistill.github.io/autodistill/base_models/dinov2/ broken link point to https://github.com/facebookresearch/dinov2/blob/main/MODEL_CARD.md

**Comment by capjamesg** [comment]
Apologies for the broken link. We had not yet published our DINOv2 documentation when we first launched Autodistill. The link will work now!
